
# https://python-poetry.org/docs/configuration/

# cache-dir = "/path/to/cache/directory"
# virtualenvs.create = true
# virtualenvs.in-project = null
# virtualenvs.options.always-copy = true
# virtualenvs.options.no-pip = false
# virtualenvs.options.no-setuptools = false
# virtualenvs.options.system-site-packages = false
# virtualenvs.path = "{cache-dir}/virtualenvs"  # /path/to/cache/directory/virtualenvs
# virtualenvs.prefer-active-python = false
# virtualenvs.prompt = "{project_name}-py{python_version}"
